import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import { formatMoney } from "../money";
import { fit, pdfMoney, safeText } from "./pdf";
import type { PayslipBreakdown, PayslipItem } from "./payslipCalc";

// Payslip PDF renderer (pure: no I/O).

export interface PayslipPdfInput {
  brandName: string;
  companyName: string;
  number: string;
  month: string;
  periodStart: string;
  periodEnd: string;
  invoiceNumber: string;
  currency: string;
  employee: { name: string; email: string; designation: string | null; department: string | null; country: string; engagement: string };
  breakdown: PayslipBreakdown;
  status: "finance_approved" | "paid";
  paidAt: string | null;
  paymentRef: string | null;
  generatedOn: string;
}

export async function renderPayslipPdf(p: PayslipPdfInput): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  doc.setTitle(`Payslip ${p.month}`);
  doc.setProducer(p.brandName);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const ink = rgb(0.13, 0.12, 0.1);
  const muted = rgb(0.45, 0.43, 0.38);
  const brand = rgb(0.13, 0.42, 0.27);
  const wash = rgb(0.94, 0.96, 0.94);
  const W = 595.28;
  const H = 841.89;
  const M = 48;
  const page: PDFPage = doc.addPage([W, H]);
  let y = H - M;
  const text = (s: string, x: number, yy: number, size = 10, f: PDFFont = font, color = ink) =>
    page.drawText(safeText(f, s), { x, y: yy, size, font: f, color });
  const right = (s: string, xr: number, yy: number, size = 10, f: PDFFont = font, color = ink) => {
    const t = safeText(f, s);
    page.drawText(t, { x: xr - f.widthOfTextAtSize(t, size), y: yy, size, font: f, color });
  };
  const cur = (minor: number) => `${pdfMoney(minor, p.currency)} ${p.currency}`;

  // Header band
  page.drawRectangle({ x: 0, y: H - 110, width: W, height: 110, color: brand });
  text(p.companyName, M, H - 52, 15, bold, rgb(1, 1, 1));
  text(p.brandName, M, H - 70, 9, font, rgb(0.85, 0.93, 0.88));
  right("PAYSLIP", W - M, H - 52, 20, bold, rgb(1, 1, 1));
  right(p.month, W - M, H - 72, 11, font, rgb(0.9, 0.96, 0.92));
  y = H - 140;

  // Details grid
  const detail = (label: string, value: string, x: number, yy: number) => {
    text(label, x, yy, 7.5, bold, muted);
    text(fit(font, safeText(font, value), 10, 230), x, yy - 13, 10);
  };
  const c2 = W / 2 + 10;
  detail("EMPLOYEE", p.employee.name, M, y);
  detail("PAYSLIP NO.", p.number, c2, y);
  y -= 34;
  detail("DESIGNATION", [p.employee.designation, p.employee.department].filter(Boolean).join(" · ") || "-", M, y);
  detail("PAY PERIOD", `${p.periodStart} to ${p.periodEnd}`, c2, y);
  y -= 34;
  detail("ENGAGEMENT / COUNTRY", `${p.employee.engagement} · ${p.employee.country}`, M, y);
  detail("BASED ON INVOICE", p.invoiceNumber, c2, y);
  y -= 34;
  detail("EMAIL", p.employee.email, M, y);
  detail("PAYMENT", p.status === "paid" ? `Paid ${p.paidAt?.slice(0, 10) ?? ""}${p.paymentRef ? ` · ref ${p.paymentRef}` : ""}` : "Approved · payment in process", c2, y);
  y -= 40;

  const section = (title: string, items: PayslipItem[], totalLabel: string, total: number) => {
    page.drawRectangle({ x: M - 6, y: y - 6, width: W - 2 * M + 12, height: 20, color: wash });
    text(title, M, y, 8.5, bold, muted);
    right(`Amount (${p.currency})`, W - M, y, 8.5, bold, muted);
    y -= 22;
    if (!items.length) {
      text("None", M, y, 9.5, font, muted);
      y -= 18;
    }
    for (const it of items) {
      text(fit(font, safeText(font, it.description), 9.5, 330), M, y, 9.5);
      if (it.detail) text(it.detail, 400, y, 9, font, muted);
      right(pdfMoney(it.amount_minor, p.currency), W - M, y, 9.5);
      y -= 6;
      page.drawLine({ start: { x: M, y }, end: { x: W - M, y }, thickness: 0.4, color: rgb(0.88, 0.88, 0.85) });
      y -= 13;
    }
    right(totalLabel, 470, y, 9.5, bold, muted);
    right(pdfMoney(total, p.currency), W - M, y, 9.5, bold);
    y -= 26;
  };
  section("EARNINGS", p.breakdown.earnings, "Gross earnings", p.breakdown.grossMinor);
  section("DEDUCTIONS", p.breakdown.deductions, "Total deductions", p.breakdown.deductionsMinor);
  section("REIMBURSEMENTS", p.breakdown.reimbursements, "Total reimbursements", p.breakdown.reimbursementsMinor);

  // Net pay box
  page.drawRectangle({ x: M - 6, y: y - 16, width: W - 2 * M + 12, height: 40, color: brand });
  text("NET PAY", M + 6, y, 11, bold, rgb(1, 1, 1));
  right(cur(p.breakdown.netMinor), W - M - 6, y, 15, bold, rgb(1, 1, 1));
  text(safeText(font, `(${formatMoney(p.breakdown.netMinor, p.currency)})`), M + 6, y - 12, 8, font, rgb(0.85, 0.93, 0.88));
  y -= 50;

  text(`Generated by ${p.brandName} on ${p.generatedOn} from approved invoice ${p.invoiceNumber}.`, M, M + 20, 8, font, muted);
  text("This is a computer-generated statement and does not need a signature. Taxes are handled as per your contract.", M, M + 8, 8, font, muted);
  return doc.save();
}

